[build]
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.11"
  NPM_VERSION = "9"
  AI_MODEL_VERSION = "2.0.0"
  ANALYTICS_VERSION = "2.0.0"
  SEO_VERSION = "2.0.0"
  CACHE_TTL = "3600"
  REALTIME_ENABLED = "true"
  SITEMAP_CACHE_TTL = "86400"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.paypal.com https://www.paypalobjects.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://www.paypalobjects.com https://www.paypal.com; font-src 'self'; form-action 'self' https://www.paypal.com; frame-src https://www.paypal.com"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[redirects]]
  from = "/daily-decision"
  to = "/"
  status = 301

[[redirects]]
  from = "/decision-maker"
  to = "/"
  status = 301

[[redirects]]
  from = "/compliments"
  to = "/"
  status = 301

[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200

# Serverless Functions Configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["sharp", "canvas"]

# Edge Functions Configuration (temporarily disabled)
# [[edge_functions]]
#   path = "/*"
#   function = "performance-optimizer"

# API Routes
[[redirects]]
  from = "/api/recommendations/*"
  to = "/.netlify/functions/recommendation-engine"
  status = 200

[[redirects]]
  from = "/api/analytics/*"
  to = "/.netlify/functions/analytics-aggregator"
  status = 200

[[redirects]]
  from = "/api/seo/*"
  to = "/.netlify/functions/seo-automation"
  status = 200

# Edge Function Routes (configured in edge function file)